/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimatedProgressBar {
    }
    interface EmojiRain {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RadioGroup {
    }
    interface ToggleButton {
        "checked": boolean;
        "clickToggleBox": () => Promise<void>;
    }
}
export interface EmojiRainCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmojiRainElement;
}
export interface ToggleButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLToggleButtonElement;
}
declare global {
    interface HTMLAnimatedProgressBarElement extends Components.AnimatedProgressBar, HTMLStencilElement {
    }
    var HTMLAnimatedProgressBarElement: {
        prototype: HTMLAnimatedProgressBarElement;
        new (): HTMLAnimatedProgressBarElement;
    };
    interface HTMLEmojiRainElementEventMap {
        "emoji-rain-start": any;
        "emoji-rain-stop": any;
    }
    interface HTMLEmojiRainElement extends Components.EmojiRain, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmojiRainElementEventMap>(type: K, listener: (this: HTMLEmojiRainElement, ev: EmojiRainCustomEvent<HTMLEmojiRainElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmojiRainElementEventMap>(type: K, listener: (this: HTMLEmojiRainElement, ev: EmojiRainCustomEvent<HTMLEmojiRainElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmojiRainElement: {
        prototype: HTMLEmojiRainElement;
        new (): HTMLEmojiRainElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRadioGroupElement extends Components.RadioGroup, HTMLStencilElement {
    }
    var HTMLRadioGroupElement: {
        prototype: HTMLRadioGroupElement;
        new (): HTMLRadioGroupElement;
    };
    interface HTMLToggleButtonElementEventMap {
        "buttonToggled": any;
    }
    interface HTMLToggleButtonElement extends Components.ToggleButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLToggleButtonElementEventMap>(type: K, listener: (this: HTMLToggleButtonElement, ev: ToggleButtonCustomEvent<HTMLToggleButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLToggleButtonElementEventMap>(type: K, listener: (this: HTMLToggleButtonElement, ev: ToggleButtonCustomEvent<HTMLToggleButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLToggleButtonElement: {
        prototype: HTMLToggleButtonElement;
        new (): HTMLToggleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "animated-progress-bar": HTMLAnimatedProgressBarElement;
        "emoji-rain": HTMLEmojiRainElement;
        "my-component": HTMLMyComponentElement;
        "radio-group": HTMLRadioGroupElement;
        "toggle-button": HTMLToggleButtonElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedProgressBar {
    }
    interface EmojiRain {
        "onEmoji-rain-start"?: (event: EmojiRainCustomEvent<any>) => void;
        "onEmoji-rain-stop"?: (event: EmojiRainCustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RadioGroup {
    }
    interface ToggleButton {
        "checked"?: boolean;
        "onButtonToggled"?: (event: ToggleButtonCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "animated-progress-bar": AnimatedProgressBar;
        "emoji-rain": EmojiRain;
        "my-component": MyComponent;
        "radio-group": RadioGroup;
        "toggle-button": ToggleButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-progress-bar": LocalJSX.AnimatedProgressBar & JSXBase.HTMLAttributes<HTMLAnimatedProgressBarElement>;
            "emoji-rain": LocalJSX.EmojiRain & JSXBase.HTMLAttributes<HTMLEmojiRainElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "radio-group": LocalJSX.RadioGroup & JSXBase.HTMLAttributes<HTMLRadioGroupElement>;
            "toggle-button": LocalJSX.ToggleButton & JSXBase.HTMLAttributes<HTMLToggleButtonElement>;
        }
    }
}
